/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    businesses: Business;
    vessels: Vessel;
    berths: Berth;
    services: Service;
    payments: Payment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    vessels: VesselsSelect<false> | VesselsSelect<true>;
    berths: BerthsSelect<false> | BerthsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'operator' | 'owner' | 'business_rep';
  fullName: string;
  idNumber: string;
  phone: string;
  address?: {
    houseName?: string | null;
    street?: string | null;
    island?: string | null;
    zip?: string | null;
  };
  photo?: (number | null) | Media;
  idCardCopy?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  registrationNumber: string;
  email?: string | null;
  phone?: string | null;
  registrationDoc?: (number | null) | Media;
  owner: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vessels".
 */
export interface Vessel {
  id: number;
  name: string;
  registrationNumber: string;
  registrationType: 'permanent' | 'temporary' | 'hourly';
  status: 'pending' | 'payment_pending' | 'active' | 'rejected' | 'blacklisted';
  finance?: {
    fee?: number | null;
    paymentStatus?: ('unpaid' | 'paid') | null;
    paymentDate?: string | null;
    /**
     * When the current payment period ends.
     */
    nextPaymentDue?: string | null;
    transactionId?: string | null;
  };
  vesselType:
    | 'DHOANI'
    | 'LAUNCH'
    | 'BOAT'
    | 'BOKKURA'
    | 'BAHTHELI'
    | 'DINGHY'
    | 'BARGE'
    | 'YACHT'
    | 'TUG'
    | 'SUBMARINE'
    | 'PASSENGER FERRY'
    | 'OTHER';
  useType: 'Passenger' | 'Fishing' | 'Cargo' | 'Diving' | 'Excursion' | 'Other';
  owner: number | User;
  operator?: (number | null) | User;
  registrationDoc?: (number | null) | Media;
  specs?: {
    length?: number | null;
    width?: number | null;
    fuelType?: ('Diesel' | 'Petrol') | null;
    engineType?: ('Inboard' | 'Outboard') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berths".
 */
export interface Berth {
  id: number;
  vessel: number | Vessel;
  planType: 'hourly' | 'daily' | 'monthly' | 'yearly';
  status?: ('active' | 'completed' | 'cancelled') | null;
  startTime: string;
  endTime?: string | null;
  location?: string | null;
  billing?: {
    /**
     * The rate at the time of booking
     */
    rateApplied?: number | null;
    totalCalculated?: number | null;
    isPaid?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  serviceType: 'cleaning' | 'water' | 'fuel' | 'waste' | 'electric' | 'loading';
  vessel: number | Vessel;
  status: 'requested' | 'payment_pending' | 'in_progress' | 'completed' | 'cancelled';
  quantity: number;
  /**
   * Calculated based on Site Settings rates.
   */
  totalCost?: number | null;
  requestDate: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  invoiceNumber?: string | null;
  vessel: number | Vessel;
  relatedBerth?: (number | null) | Berth;
  relatedService?: (number | null) | Service;
  amount: number;
  status: 'unpaid' | 'paid' | 'overdue' | 'cancelled';
  method?: ('cash' | 'bank_transfer' | 'online' | 'cheque') | null;
  paidAt?: string | null;
  proofOfPayment?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'vessels';
        value: number | Vessel;
      } | null)
    | ({
        relationTo: 'berths';
        value: number | Berth;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  idNumber?: T;
  phone?: T;
  address?:
    | T
    | {
        houseName?: T;
        street?: T;
        island?: T;
        zip?: T;
      };
  photo?: T;
  idCardCopy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  registrationNumber?: T;
  email?: T;
  phone?: T;
  registrationDoc?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vessels_select".
 */
export interface VesselsSelect<T extends boolean = true> {
  name?: T;
  registrationNumber?: T;
  registrationType?: T;
  status?: T;
  finance?:
    | T
    | {
        fee?: T;
        paymentStatus?: T;
        paymentDate?: T;
        nextPaymentDue?: T;
        transactionId?: T;
      };
  vesselType?: T;
  useType?: T;
  owner?: T;
  operator?: T;
  registrationDoc?: T;
  specs?:
    | T
    | {
        length?: T;
        width?: T;
        fuelType?: T;
        engineType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berths_select".
 */
export interface BerthsSelect<T extends boolean = true> {
  vessel?: T;
  planType?: T;
  status?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  billing?:
    | T
    | {
        rateApplied?: T;
        totalCalculated?: T;
        isPaid?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  serviceType?: T;
  vessel?: T;
  status?: T;
  quantity?: T;
  totalCost?: T;
  requestDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  invoiceNumber?: T;
  vessel?: T;
  relatedBerth?: T;
  relatedService?: T;
  amount?: T;
  status?: T;
  method?: T;
  paidAt?: T;
  proofOfPayment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  platformName?: string | null;
  supportPhone?: string | null;
  supportEmail?: string | null;
  hourlyRate: number;
  dailyRate: number;
  monthlyRate: number;
  yearlyRate: number;
  taxPercentage?: number | null;
  cleaningRate?: number | null;
  waterRate?: number | null;
  fuelRate?: number | null;
  wasteRate?: number | null;
  electricRate?: number | null;
  loadingRate?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  platformName?: T;
  supportPhone?: T;
  supportEmail?: T;
  hourlyRate?: T;
  dailyRate?: T;
  monthlyRate?: T;
  yearlyRate?: T;
  taxPercentage?: T;
  cleaningRate?: T;
  waterRate?: T;
  fuelRate?: T;
  wasteRate?: T;
  electricRate?: T;
  loadingRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}